### ISSUE TITLE
Blocks applied by YT (question)

### ISSUE THREAD

**Issue by Pamilg9** [iv-org/inv_sig_helper#19]
Blocking problems:
1. The initial player response is not valid (Video not available)
2. Watch on the latest version of YT
3. 403 error vs İP(server) blocking 
      
Does this tool prevent them?
Thank you in advance. I read it, but I didn't fully understand it

**Comment by techmetx11** [comment]
This tool (as it is right now) only decrypts YouTube stream signatures and n-signatures that it gets provided, then passes them to the client, to bypass throttling and blocking related to those.
It does not help against IP blocking, or any other YouTube protection.

**Comment by Pamilg9** [comment]
> This tool (as it is right now) only decrypts YouTube stream signatures and n-signatures that it gets provided via YouTube's own JavaScript code, then passes them to the client, to bypass throttling and blocking related to those. It does not help against IP blocking, or any other YouTube protection.

When I say IP, I mean invidious instances

**Comment by techmetx11** [comment]
> > This tool (as it is right now) only decrypts YouTube stream signatures and n-signatures that it gets provided via YouTube's own JavaScript code, then passes them to the client, to bypass throttling and blocking related to those. It does not help against IP blocking, or any other YouTube protection.
> 
> When I say IP, I mean invidious instances. YouTube tries to ban all IP addresses of all Invidious instances so they can force users to use the official website/app. I chose the right title for the issue

Again, inv_sig_helper will not help with YouTube's IP blocking, That is out of scope for this project

**Comment by SamantazFox** [comment]
@Pamilg9 as techmetx11 said, this tool's purpose is to decipher `/videoplayback` URLs. It is not meant to help with blocked instances and/or IP addresses. We have other tools for that purpose.

**Comment by Pamilg9** [comment]
> @Pamilg9techmetx11-in dediyi kimi, bu alətin məqsədi URL-ləri deşifrə etməkdir `/videoplayback`. O, bloklanmış nümunələr və/və ya IP ünvanları ilə kömək etmək üçün nəzərdə tutulmayıb. Bunun üçün başqa alətlərimiz də var.

Which?
How do I solve the "Watch on the latest version of YouTube"?

**Comment by SamantazFox** [comment]
You need to change your IP, for example with https://github.com/iv-org/smart-ipv6-rotator

**Comment by unixfox** [comment]
The correct answers has been given. Closing.
