### ISSUE TITLE
[debug] Videos: Error when parsing video URL

### ISSUE THREAD

**Issue by kkwpsi** [iv-org/inv_sig_helper#23]
Hello,

I'm using Invidious (2024.09.20-a021b930) and inv_sig_helper on Debian 12 (w/o Docker). Apps are running by the same user. Inv_sig_helper has a unix socket in /home/apps/apps/invidious/tmp/inv_sig_helper.sock. Invidious has a config parameter:

> signature_server: /home/apps/apps/invidious/tmp/inv_sig_helper.sock

The programs start. However, at a later stage I do not see that Invidious successfully contacts inv_sig_helper. Nothing appears in the inv_sig_helper journal logs. In turn, in the Invidious logs, when I want to play any clip, many entries appear like:

> [info] 302 GET /latest_version?id=<some_id>&itag=18 29.38ms
> [debug] Videos: Error when parsing video URL

As a result, with "signature_server" set, no clip can play.
If I remove the "signature_server" setting, Invidious works normally.

Any advice?

**Comment by friedkiwi** [comment]
The signature server itself doesn't know about the URL being played, this is something that should probably be logged from https://github.com/iv-org/invidious itself. The latest code changes do include additional logging so you can see that invidious is trying to use it.

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).
