### ISSUE TITLE
Docker: Error occurred while trying to bind: Permission denied (os error 13)

### ISSUE THREAD

**Issue by chrisafraser** [iv-org/inv_sig_helper#29]
I am trying to deploy inv_sig_helper to my nomad cluster, and when I use the --tcp arguments in the docker container it fails to start with the following error message

```
[2024-10-11T13:42:26Z ERROR inv_sig_helper_rust] Error occurred while trying to bind: Permission denied (os error 13)
```

I am able to replace the docker container image in my job with a test image and forward ports (static or dynamically) without any issues so I am trying to figure out why inv_sig_helper is having permission issues. If I run via command line with ``docker run -d -p 12999:12999 quay.io/invidious/inv-sig-helper:latest --tcp`` on the same worker nodes, it seems to work fine.

Looking through the code here, https://github.com/iv-org/inv_sig_helper/blob/master/src/main.rs#L64 it doesnt seem like inv_sig_helper is doing anything special?

Any ideas on how to debug this further? I tried setting env RUST_LOG=trace and didn't see much related to the tcp listener.

**Comment by unixfox** [comment]
Podman is most likely not giving the binding permission to the process.
