### ISSUE TITLE
[Help] Working URL's...

### ISSUE THREAD

**Issue by Elite** [iv-org/inv_sig_helper#35]
Hi,

I am trying to use this docker image to serve as a signature decoder for my userscript which uses `InnerTube` `MWEB` client to get urls' which are not downloadable due to signature requirement, I tried supplying the decoded `n` and `s` signatures but it still fails (403) to give me a working streamable url. Can anybody help me understand how to use the decrypted values and what values are needed for getting a working url.

Thanks

**Comment by unixfox** [comment]
You should use https://github.com/LuanRT/YouTube.js instead.

It's easier to use it in a generic way.

inv_sig_helper was designed only for Invidious.

**Comment by Elite** [comment]
Can you still share what url parameters I need to send from MWEB extracted urls which needs to be decoded using the inv_sig_helper ?
