### ISSUE TITLE
cargo build problems as non-root user

### ISSUE THREAD

**Issue by matzzze** [iv-org/inv_sig_helper#39]
I get the inv_sig_helper running only compiled when I use root user

System information
* LXC container running Ubuntu 24.04.1 LTS x86_64
* Installed dependencies:
* <code>rustc 1.81.0 (eeb90cda1 2024-09-04)</code>
* <code>GNU patch 2.7.6</code>
* <code>libssl-dev 3.0.13-0ubuntu3.4</code>
* <code>cargo 1.81.0 (2dbb1af80 2024-08-20)</code>

<details>
<summary>Error message installing as user invidious</summary>
<code>cargo build --release
   Compiling proc-macro2 v1.0.81
   Compiling unicode-ident v1.0.12
   Compiling quote v1.0.36
   Compiling syn v2.0.60
   Compiling libc v0.2.153
   Compiling autocfg v1.2.0
   Compiling memchr v2.7.2
   Compiling cfg-if v1.0.0
   Compiling cc v1.0.95
   Compiling pin-project-lite v0.2.14
   Compiling lock_api v0.4.12
   Compiling once_cell v1.19.0
   Compiling bytes v1.6.0
   Compiling parking_lot_core v0.9.10
   Compiling slab v0.4.9
   Compiling log v0.4.22
   Compiling smallvec v1.13.2
   Compiling scopeguard v1.2.0
   Compiling futures-core v0.3.30
   Compiling futures-sink v0.3.30
   Compiling futures-channel v0.3.30
   Compiling parking_lot v0.12.2
   Compiling signal-hook-registry v1.4.2
   Compiling socket2 v0.5.6
   Compiling mio v0.8.11
   Compiling num_cpus v1.16.0
   Compiling futures-macro v0.3.30
   Compiling tokio-macros v2.2.0
   Compiling vcpkg v0.2.15
   Compiling pin-utils v0.1.0
   Compiling pkg-config v0.3.30
   Compiling futures-io v0.3.30
   Compiling futures-task v0.3.30
   Compiling futures-util v0.3.30
   Compiling openssl-sys v0.9.103
   Compiling tokio v1.37.0
   Compiling itoa v1.0.11
   Compiling tracing-core v0.1.32
   Compiling fnv v1.0.7
   Compiling http v1.1.0
   Compiling tracing v0.1.40
   Compiling httparse v1.8.0
   Compiling foreign-types-shared v0.1.1
   Compiling hashbrown v0.14.3
   Compiling openssl v0.10.66
   Compiling equivalent v1.0.1
   Compiling indexmap v2.2.6
   Compiling foreign-types v0.3.2
   Compiling tokio-util v0.7.10
   Compiling http-body v1.0.0
   Compiling aho-corasick v1.1.3
   Compiling openssl-macros v0.1.1
   Compiling pin-project-internal v1.1.5
   Compiling tinyvec_macros v0.1.1
   Compiling bitflags v2.5.0
   Compiling native-tls v0.2.11
   Compiling regex-syntax v0.8.3
   Compiling try-lock v0.2.5
   Compiling want v0.3.1
   Compiling regex-automata v0.4.6
   Compiling tinyvec v1.6.0
   Compiling pin-project v1.1.5
   Compiling h2 v0.4.4
   Compiling rquickjs-sys v0.6.0
   Compiling openssl-probe v0.1.5
   Compiling serde v1.0.199
   Compiling percent-encoding v2.3.1
   Compiling tower-service v0.3.2
   Compiling tower-layer v0.3.2
   Compiling crossbeam-utils v0.8.19
   Compiling tower v0.4.13
   Compiling form_urlencoded v1.2.1
   Compiling hyper v1.3.1
   Compiling unicode-normalization v0.1.23
   Compiling regex v1.10.4
   Compiling utf8parse v0.2.2
   Compiling event-listener v2.5.3
   Compiling unicode-bidi v0.3.15
   Compiling idna v0.5.0
   Compiling async-lock v2.8.0
   Compiling anstyle-parse v0.2.5
   Compiling hyper-util v0.1.3
   Compiling tokio-native-tls v0.3.1
   Compiling http-body-util v0.1.1
   Compiling ryu v1.0.17
   Compiling anstyle-query v1.1.1
   Compiling rustls-pki-types v1.5.0
   Compiling base64 v0.22.0
   Compiling is_terminal_polyfill v1.70.1
   Compiling anstyle v1.0.8
   Compiling colorchoice v1.0.2
   Compiling anstream v0.6.15
   Compiling rustls-pemfile v2.1.2
   Compiling serde_urlencoded v0.7.1
   Compiling hyper-tls v0.6.0
   Compiling crossbeam-queue v0.3.11
   Compiling lazy-regex-proc_macros v3.1.0
   Compiling rquickjs-core v0.6.0
error[E0658]: use of unstable library feature 'offset_of'
   --> /home/invidious/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rquickjs-core-0.6.0/src/runtime/schedular.rs:126:26
    |
126 |         debug_assert_eq!(offset_of!(Task<F>, future), offset_of!(Task<u8>, future));
    |                          ^^^^^^^^^
    |
    = note: see issue #106655 <https://github.com/rust-lang/rust/issues/106655> for more information

error[E0658]: use of unstable library feature 'offset_of'
   --> /home/invidious/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rquickjs-core-0.6.0/src/runtime/schedular.rs:126:55
    |
126 |         debug_assert_eq!(offset_of!(Task<F>, future), offset_of!(Task<u8>, future));
    |                                                       ^^^^^^^^^
    |
    = note: see issue #106655 <https://github.com/rust-lang/rust/issues/106655> for more information

error[E0658]: use of unstable library feature 'offset_of'
 --> /home/invidious/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rquickjs-core-0.6.0/src/runtime/schedular.rs:4:11
  |
4 |     mem::{offset_of, ManuallyDrop},
  |           ^^^^^^^^^
  |
  = note: see issue #106655 <https://github.com/rust-lang/rust/issues/106655> for more information

For more information about this error, try `rustc --explain E0658
error: could not compile `rquickjs-core` (lib) due to 3 previous errors
</code>
</details>

<details>
<summary>Installing as root user returns warnings</summary>
<code>
cargo build --release
   Compiling proc-macro2 v1.0.81
   Compiling unicode-ident v1.0.12
   Compiling quote v1.0.36
   Compiling syn v2.0.60
   Compiling libc v0.2.153
   Compiling autocfg v1.2.0
   Compiling memchr v2.7.2
   Compiling cfg-if v1.0.0
   Compiling pin-project-lite v0.2.14
   Compiling cc v1.0.95
   Compiling lock_api v0.4.12
   Compiling parking_lot_core v0.9.10
   Compiling once_cell v1.19.0
   Compiling bytes v1.6.0
   Compiling slab v0.4.9
   Compiling futures-core v0.3.30
   Compiling log v0.4.22
   Compiling smallvec v1.13.2
   Compiling scopeguard v1.2.0
   Compiling futures-sink v0.3.30
   Compiling futures-channel v0.3.30
   Compiling parking_lot v0.12.2
   Compiling num_cpus v1.16.0
   Compiling socket2 v0.5.6
   Compiling signal-hook-registry v1.4.2
   Compiling mio v0.8.11
   Compiling futures-macro v0.3.30
   Compiling tokio-macros v2.2.0
   Compiling pin-utils v0.1.0
   Compiling vcpkg v0.2.15
   Compiling pkg-config v0.3.30
   Compiling futures-io v0.3.30
   Compiling futures-task v0.3.30
   Compiling futures-util v0.3.30
   Compiling openssl-sys v0.9.103
   Compiling tokio v1.37.0
   Compiling itoa v1.0.11
   Compiling tracing-core v0.1.32
   Compiling fnv v1.0.7
   Compiling http v1.1.0
   Compiling tracing v0.1.40
   Compiling foreign-types-shared v0.1.1
   Compiling equivalent v1.0.1
   Compiling openssl v0.10.66
   Compiling hashbrown v0.14.3
   Compiling httparse v1.8.0
   Compiling indexmap v2.2.6
   Compiling foreign-types v0.3.2
   Compiling tokio-util v0.7.10
   Compiling http-body v1.0.0
   Compiling aho-corasick v1.1.3
   Compiling pin-project-internal v1.1.5
   Compiling openssl-macros v0.1.1
   Compiling bitflags v2.5.0
   Compiling try-lock v0.2.5
   Compiling regex-syntax v0.8.3
   Compiling native-tls v0.2.11
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling regex-automata v0.4.6
   Compiling want v0.3.1
   Compiling pin-project v1.1.5
   Compiling h2 v0.4.4
   Compiling rquickjs-sys v0.6.0
   Compiling tower-layer v0.3.2
   Compiling crossbeam-utils v0.8.19
   Compiling openssl-probe v0.1.5
   Compiling serde v1.0.199
   Compiling tower-service v0.3.2
   Compiling percent-encoding v2.3.1
   Compiling form_urlencoded v1.2.1
   Compiling tower v0.4.13
   Compiling hyper v1.3.1
   Compiling regex v1.10.4
   Compiling unicode-normalization v0.1.23
   Compiling utf8parse v0.2.2
   Compiling event-listener v2.5.3
   Compiling unicode-bidi v0.3.15
   Compiling idna v0.5.0
   Compiling async-lock v2.8.0
   Compiling anstyle-parse v0.2.5
   Compiling hyper-util v0.1.3
   Compiling tokio-native-tls v0.3.1
   Compiling http-body-util v0.1.1
   Compiling base64 v0.22.0
   Compiling is_terminal_polyfill v1.70.1
   Compiling anstyle v1.0.8
   Compiling anstyle-query v1.1.1
   Compiling colorchoice v1.0.2
   Compiling ryu v1.0.17
   Compiling rustls-pki-types v1.5.0
   Compiling rustls-pemfile v2.1.2
   Compiling serde_urlencoded v0.7.1
   Compiling anstream v0.6.15
   Compiling hyper-tls v0.6.0
   Compiling crossbeam-queue v0.3.11
   Compiling lazy-regex-proc_macros v3.1.0
   Compiling rquickjs-core v0.6.0
   Compiling url v2.5.0
   Compiling env_filter v0.1.2
   Compiling futures-executor v0.3.30
   Compiling encoding_rs v0.8.34
   Compiling sync_wrapper v0.1.2
   Compiling humantime v2.1.0
   Compiling ipnet v2.9.0
   Compiling mime v0.3.17
   Compiling reqwest v0.12.4
   Compiling env_logger v0.11.5
   Compiling futures v0.3.30
   Compiling rquickjs v0.6.0
   Compiling lazy-regex v3.1.0
   Compiling tub v0.3.7
   Compiling inv_sig_helper_rust v0.1.0 (/home/invidious/inv_sig_helper)
warning: static `SIG_FUNCTION_NAME` is never used
  --> src/consts.rs:40:12
   |
40 | pub static SIG_FUNCTION_NAME: &str = "decrypt_sig";
   |            ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field `js_runtime` is never read
  --> src/jobs.rs:58:5
   |
57 | pub struct JavascriptInterpreter {
   |            --------------------- field in this struct
58 |     js_runtime: AsyncRuntime,
   |     ^^^^^^^^^^

warning: unused `Result` that must be used
  --> src/main.rs:84:21
   |
84 |                     remove_file(socket_url).await;
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled
   = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
   |
84 |                     let _ = remove_file(socket_url).await;
   |                     +++++++

warning: `inv_sig_helper_rust` (bin "inv_sig_helper_rust") generated 3 warnings
    Finished `release` profile [optimized] target(s) in 6m 18s

</code>
</details>

<details>
<summary>invidious log</summary>
<code>
2024-12-13 11:55:05 UTC [info] SigHelper: Using helper at 'localhost:12999'
[production] Invidious is ready to lead at http://0.0.0.0:3000
2024-12-13 11:55:05 UTC [info] jobs: running ClearExpiredItems job
2024-12-13 11:55:05 UTC [info] jobs: ClearExpiredItems done.
2024-12-13 11:55:05 UTC [info] InstanceListRefreshJob: Done, sleeping for 30 minutes
2024-12-13 11:55:12 UTC [info] 302 GET / 6.82ms
2024-12-13 11:55:12 UTC [info] 200 GET /feed/subscriptions 159.24ms
2024-12-13 11:55:13 UTC [info] ytimg_pool: Creating a new HTTP pool for "https://i.ytimg.com"
2024-12-13 11:55:13 UTC [info] 304 GET /vi/hYrn9P-TBSo/mqdefault.jpg 247.4ms
2024-12-13 11:55:13 UTC [info] 304 GET /vi/uRBgQAwRagQ/mqdefault.jpg 178.06ms
2024-12-13 11:55:13 UTC [info] 304 GET /vi/ENtW5-bV_Yc/mqdefault.jpg 146.5ms
2024-12-13 11:55:13 UTC [info] 200 GET /vi/TyfhuAjIHg0/mqdefault.jpg 36.95ms
2024-12-13 11:55:13 UTC [info] 304 GET /vi/pgGrQjYcm5A/mqdefault.jpg 22.76ms
2024-12-13 11:55:13 UTC [info] 304 GET /vi/TgKJA-0Z5vc/mqdefault.jpg 23.87ms
2024-12-13 11:55:13 UTC [info] 200 GET /vi/R_ktlT-z62U/mqdefault.jpg 9.82ms
2024-12-13 11:55:13 UTC [info] 200 GET /vi/dkwZob-HxSU/mqdefault.jpg 8.95ms
2024-12-13 11:55:13 UTC [info] 200 GET /vi/3EI6Y6PVgLo/mqdefault.jpg 10.74ms
2024-12-13 11:55:13 UTC [info] 200 GET /api/v1/auth/subscriptions 14.75ms
2024-12-13 11:55:26 UTC [error] get_video: uRBgQAwRagQ : Error: non 200 status code. Youtube API returned status code 400. See <a href="https://docs.invidious.io/youtube-errors-explained/"> https://docs.invidious.io/youtube-errors-explained/</a> for troubleshooting.
2024-12-13 11:55:26 UTC [warn] i18n: Missing translation key "Error: non 200 status code. Youtube API returned status code 400. See <a href="https://docs.invidious.io/youtube-errors-explained/"> https://docs.invidious.io/youtube-errors-explained/</a> for troubleshooting."
2024-12-13 11:55:26 UTC [info] 500 GET /watch?v=uRBgQAwRagQ 154.87ms
2024-12-13 11:55:26 UTC [info] 200 GET /api/v1/auth/subscriptions 14.91ms
2024-12-13 11:56:24 UTC [info] 200 POST /api/v1/auth/notifications 70027.31ms
</code>
</details>

<details>
<summary>inv_sig_helper log</summary>
<code>
[2024-12-13T11:54:56Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-13T11:54:56Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/f8f53e1a/player_ias.vflset/en_US/base.js
[2024-12-13T11:54:56Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
[2024-12-13T11:54:56Z INFO  inv_sig_helper_rust::player] sig code: var FM0;var Z1={r5:function(k,y){var q=k[0];k[0]=k[y%k.length];k[y%k.length]=q},
    w8:function(k,y){k.splice(0,y)},
    G9:function(k){k.reverse()}};FM0=function(k){k=k.split("");Z1.w8(k,2);Z1.G9(k,62);Z1.r5(k,5);Z1.w8(k,1);Z1.G9(k,18);Z1.w8(k,2);Z1.G9(k,26);return k.join("")}
[2024-12-13T11:54:56Z INFO  inv_sig_helper_rust] Successfully fetched player
</code>
</details>

it does work that way, but maybe it makes sense to add that into the documentation for dumb users like myself?

**Comment by unixfox** [comment]
Hello, this sounds like a configuration issue on your side.

As maintainers, we do not have a lot of free time so you should ask your question on our [matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).
