### ISSUE TITLE
sig helper panics occasionally during player update, preventing invidious from starting

### ISSUE THREAD

**Issue by 999eagle** [iv-org/inv_sig_helper#4]
i'm currently running `inv_sig_helper` on my invidious instance (`iv.catgirl.cloud`) with the patches from https://github.com/iv-org/invidious/pull/4772 applied to use the sig helper. every now and then when one of the workers is restarted after an hour of uptime, it doesn't start back up properly because it tries sending a force update to the sig helper, which then panics and doesn't return any response, making invidious wait forever.

here's the rust backtrace (somewhat reproducible by restarting a single invidious worker process several times until it hangs on start):
```
thread 'tokio-runtime-worker' panicked at src/player.rs:62:80:
called `Option::unwrap()` on a `None` value                                                                                                            
stack backtrace:                                                                                                                                       
   0: rust_begin_unwind                                                                                                                                
   1: core::panicking::panic_fmt                                                                                                                       
   2: core::panicking::panic                                                                                                                           
   3: core::option::unwrap_failed                                                                                                                      
   4: inv_sig_helper_rust::player::fetch_update::{{closure}}                                                                                           
   5: inv_sig_helper_rust::process_socket::{{closure}}::{{closure}}                                                                                    
   6: tokio::runtime::task::core::Core<T,S>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run
  10: tokio::runtime::context::set_scheduler
  11: tokio::runtime::context::runtime::enter_runtime
  12: tokio::runtime::scheduler::multi_thread::worker::run
  13: tokio::runtime::task::core::Core<T,S>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

by patching `inv_sig_helper` to print the js url it fetches before trying to match the `NSIG_FUNCTION_ARRAY`, this is the player js url that leads to the panic: `https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js`

update: here's another player js url that leads to the same panic `https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js`

**Comment by MMaster** [comment]
FYI: This now happens for all players on my instance. No matter how many times I restart the inv_sig_helper.

**Comment by techmetx11** [comment]
YouTube changed the script again to break extraction

**Comment by techmetx11** [comment]
Might be fixed in latest commit https://github.com/iv-org/inv_sig_helper/commit/deae9055ca9e3b210fc4c20e279873d2eaaaaab7

**Comment by unixfox** [comment]
Thank you @techmetx11 for the very fast fix!
